baseURL = 'https://raffaelecalza.me'
languageCode = 'it-it'
title = '$ you@raffaelecalza: ~/'
theme = 'custom-theme'

[params]
[params.welcome]
    message = "Hi there 👋, I'm"
    messageSpan = "Raffaele"
    quote = "\"Just your friendly neighborhood developer\""

[params.contacts]
    gpg = "0000 0000 0000 0000 0000 0000 0000 0000 0000 0000"
    telegram = "#"
    instagram = "#"
    linkedin = "#"
    twitter = "#"
    github = "#"