baseURL = 'https://raffaelecalza.me'
languageCode = 'it-it'
title = '$ you@raffaelecalza: ~/'
theme = 'custom-theme'
[markup]
[markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = 'monokai'
    tabWidth = 4

[params]
[params.welcome]
    message = "Hi there 👋, I'm"
    messageSpan = "Raffaele"
    quote = "\"Just your friendly neighborhood developer\""

[params.contacts]
    gpg = "0000 0000 0000 0000 0000 0000 0000 0000 0000 0000"
    telegram = "#"
    instagram = "#"
    linkedin = "#"
    twitter = "#"
    github = "#"