baseURL = 'https://raffaelecalza.me'
languageCode = 'en-en'
title = "raffaele."
disableKinds = ["sitemap", "RSS", "taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true

[markup]
[markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4

[params]
version = "v1.0.2"
repoUrl = "https://github.com/raffaelecalza/personal-website"
[params.welcome]
    profileImage = "/img/avatar.png"
    message = "Hi there 👋, I'm"
    messageSpan = "Raffaele"
    quote = "CyberSec student, technology enthusiast and CLI lover"

[params.contacts]
    gpg = "A004 55C8 2518 4242 D0EB 5536 6B1C 539C 8990 1933"
    gpgUrl = "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6B1C539C89901933"
    email = "hello [at] raffaelecalza [dot] me"
    telegram = "@raffaelecalza"
    linkedin = "https://www.linkedin.com/in/raffaelecalza/"
    twitter = "https://twitter.com/raffaelecalza"
    github = "https://github.com/raffaelecalza"