baseURL = 'https://raffaelecalza.me'
languageCode = 'it-it'
title = '$ you@raffaelecalza: ~/'
theme = 'custom-theme'

[params]
[params.welcome]
    message = "Hi there 👋, I'm Raffaele"
    quote = "\"Just your friendly neighborhood developer\""

[params.skills]
    